name: CI

on:
  schedule:
    - cron: "0 9,12,15,18 * * 1-5"
  push:
    branches:    
      - 'main'
  workflow_dispatch:

env:
  TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
  TELEGRAM_CHAT: ${{ secrets.TELEGRAM_CHAT }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          repository: fabianonline/telegram.sh
          path: telegram.sh
      - run: mv telegram.sh/telegram .
      - run: ./main.sh

